<!doctype html>
<html class="no-js" lang="">

<head>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="icon" href="/assets/img/logo-32x32.png" sizes="32x32"/>
    <link rel="icon" href="/assets/img/logo-192x192.png" sizes="192x192"/>

    <title>Stories | Indian Detailing Garage</title>

    <link href="/assets/css/plugins.css" rel="stylesheet"/>
    <link rel="stylesheet" href="/assets/css/style.css">

</head>

<body class="v-dark bg-dots dsn-ajax">


<div id="dsn_preloader" class="preloader">

    <div class="dsnload p-absolute">
        <span class="dsnload__row">
            <span class="dsnload__img">
            <img src="/assets/img/logo-light.png" class="logo-dark" alt="IndianDetailingGarage" decoding="async" loading="lazy"/>
            <img src="/assets/img/logo.png" class="logo-light" alt="IndianDetailingGarage" decoding="async" loading="lazy"/>
            </span>
        </span>
        <span class="dsnload__row dsnload__row--sibling">
            <span class="dsnload__img">
                 <img src="/assets/img/logo-light.png" class="logo-dark" alt="IndianDetailingGarage" decoding="async" loading="lazy"/>
            <img src="/assets/img/logo.png" class="logo-light" alt="IndianDetailingGarage" decoding="async" loading="lazy"/>
            </span>
        </span>
        <span class="dsnload__row dsnload__row--sibling">
            <span class="dsnload__img">
                <img src="/assets/img/logo-light.png" class="logo-dark" alt="IndianDetailingGarage" decoding="async" loading="lazy"/>
            <img src="/assets/img/logo.png" class="logo-light" alt="IndianDetailingGarage" decoding="async" loading="lazy"/>
            </span>
        </span>
        <span class="dsnload__row dsnload__row--sibling">
            <span class="dsnload__img">
               <img src="/assets/img/logo-light.png" class="logo-dark" alt="IndianDetailingGarage" decoding="async" loading="lazy"/>
            <img src="/assets/img/logo.png" class="logo-light" alt="IndianDetailingGarage" decoding="async" loading="lazy"/>
            </span>
        </span>


    </div>
    <svg width="100%" height="100%" viewBox="0 0 100 100" class="v-middle" preserveAspectRatio="xMinYMin meet"
         fill="none">
        <linearGradient id="linearColors" x1="0" y1="0" x2="1" y2="1">
            <stop offset="0%" stop-color="var(--theme-color)"></stop>
            <stop offset="50%" stop-color="var(--border-color)"></stop>
            <stop offset="100%" stop-color="var(--assistant-color)"></stop>
        </linearGradient>
        <path class="dsn-progress-path" d="M50,1 a49,49 0 0,1 0,98 a49,49 0 0,1 0,-98"/>
    </svg>
    <div class="loading-circle v-middle">
        <p class="loading-count v-middle">0</p>
    </div>

    <span class="loading-text text-uppercase mt-30 dsn-container">Loading ...</span>
    <div class="bg-load background-section d-flex align-items-end">
        <svg class="dsn-separator-bottom dsn-icon-assistant-color" width="100%" height="100%" viewBox="0 0 100 10"
             preserveAspectRatio="none">
            <path class="path-anim separator__path" data-dsn-to="M 0 0 C 40 0 55 0 100 0 L 0 0 Z"
                  vector-effect="non-scaling-stroke" d="M 0 0 C 40 16 75 10 100 0 L 0 0 Z"></path>
        </svg>
    </div>

</div>

<main id="main_root" class="main-root">

<?php include('common/header.php'); ?>

    <!-- ========== Header Normal========== -->
    <header id="dsn_header" class="dsn-header-animation  header-normal ">
        <div class="entry-header p-relative over-hidden">

            <div id="hero_content" class="d-flex p-relative h-100 dsn-hero-parallax-title container">
                <div class="content p-relative ">
                    <div class="intro-project w-100">
                        <div class="intro-title ">
                            <div id="hero_title">
                                <h1 class="title title-org" data-dsn-ajax="title">Our Stories</h1>
                            </div>
                            <p class="subtitle-meta metas p-relative mt-10">NEWS & IDEAS</p>
                        </div>

                    </div>

                </div>

            </div>


        </div>


        <a href="#page_wrapper" rel="nofollow" class="dsn-scroll-bottom"
           data-dsn-option='{"ease": "power4.inOut" , "duration" : 1.5}'>
            <div class="text">SCROLL</div>
        </a>

    </header>
    <!-- ========== End Header Normal ========== -->

    <div id="page_wrapper" class="wrapper">

        <!-- ========== Stories ========== -->
        <div class="root-blog container section-margin  dsn-blog">
            <?php
            foreach ($blogs as $blog) {
            ?>
            <article class="blog-item p-relative pt-50 pb-50 border-bottom">
                <div class="blog-item-inner p-relative">
                    <div class="left-box">
                        <a href="/blog/<?= $blog['slug'] ?>" class="effect-ajax word-wrap" rel="bookmark">
                            <h4 class="title-block"><?= $blog['title'] ?></h4>
                        </a>

                        <div class="link mt-15">
                            <span class="font-caps heading-color"> <?= date('F d, Y', intval($blog['created'])) ?> </span>
                        </div>
                    </div>
                    <div class="right-box">
                        <p class="max-w570">
                            <?= $blog['shortdescription'] ?>
                        </p>
                        <!-- <div class="metas has-separates fz-14 blog-category mt-5">
                            <span class="mt-10">Uncategorized</span>
                        </div> -->
                    </div>
                </div>
            </article>
            <?php
            }
            ?>
            <div class="type-p-nav">
                <div class="dsn-pagination  p-relative d-flex align-items-center">
                    <?php
                    $pagi = 1;
                    $postCount2 = $postCount;
                    do {
                        if($page == $pagi) {
                    ?>
                    <span aria-current="page" class="page-numbers current">
                        <span class="dsn-numbers dsn-heading-title title-tag">
                            <span class="number"><?= $pagi ?></span>
                        </span>
                    </span>
                    <?php
                        } else {
                    ?>
                    <a class="page-numbers" href="/blog?page=<?= $pagi ?>">
                        <span class="dsn-numbers dsn-heading-title title-tag">
                            <span class="number"><?= $pagi ?></span>
                        </span>
                    </a>
                    <?php
                        }
                        $postCount2 = $postCount2 - 10;
                        $pagi = $pagi + 1;
                    } while ($postCount2 > 0);
                    ?>
                    
                    
                    <a class="next page-numbers" href="<?php
                    $remaining = $postCount - ( $page * 10 );
                    echo $remaining > 0 ? "/blog?page=" . ($page + 1) : "#";
                    ?>">
                        <svg viewBox="0 0 52 52" xmlns="http://www.w3.org/2000/svg" width="100%" height="100%"
                             fill="#fff">
                            <path d="M3 26.7h39.5v3.5c0 .3.1.5.4.6.2.1.5.1.7-.1l5.9-4.2c.2-.1.3-.3.3-.5s-.1-.4-.3-.5l-5.9-4.2c-.1-.1-.3-.1-.4-.1-.1 0-.2 0-.3.1-.2.1-.4.3-.4.6v3.5H3c-.4 0-.7.3-.7.7 0 .3.3.6.7.6z"></path>
                        </svg>
                        <span class="sm-title-block dsn-heading-title ">Next</span>
                    </a>
                </div>
            </div>
        </div>
        <!-- ========== End Stories ========== -->

<?php include('common/footer.php'); ?>

    </div>





</main>

<!-- ========== Cursor ========== -->
<div id="dsn_cursor" class="ball"></div>
<div id="dsn_cursor_inner" class="ball"></div>
<!-- ========== End Cursor ========== -->

<?php include('common/social-style.php'); ?>

<!-- ========== Line BG ========== -->
<div id="line_head"><span class="container"></span></div>
<!-- ========== End Line BG ========== -->

<script src="/assets/js/jquery-3.1.1.min.js"></script>
<script src="/assets/js/plugins.min.js"></script>
<script src="/assets/js/plugins/dsn-grid.min.js"></script>
<script src="/assets/js/custom.js"></script>

</body>

</html>
