<!doctype html>
<html class="no-js" lang="">

<head>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="icon" href="/assets/img/logo-32x32.png" sizes="32x32"/>
    <link rel="icon" href="/assets/img/logo-192x192.png" sizes="192x192"/>

    <title><?= $blog['title'] ?> | Indian Detailing Garage</title>

    <link href="/assets/css/plugins.css" rel="stylesheet"/>
    <link rel="stylesheet" href="/assets/css/style.css">

</head>

<body class="v-dark bg-dots dsn-ajax">


<div id="dsn_preloader" class="preloader">

    <div class="dsnload p-absolute">
        <span class="dsnload__row">
            <span class="dsnload__img">
            <img src="/assets/img/logo-light.png" class="logo-dark" alt="IndianDetailingGarage" decoding="async" loading="lazy"/>
            <img src="/assets/img/logo.png" class="logo-light" alt="IndianDetailingGarage" decoding="async" loading="lazy"/>
            </span>
        </span>
        <span class="dsnload__row dsnload__row--sibling">
            <span class="dsnload__img">
                 <img src="/assets/img/logo-light.png" class="logo-dark" alt="IndianDetailingGarage" decoding="async" loading="lazy"/>
            <img src="/assets/img/logo.png" class="logo-light" alt="IndianDetailingGarage" decoding="async" loading="lazy"/>
            </span>
        </span>
        <span class="dsnload__row dsnload__row--sibling">
            <span class="dsnload__img">
                <img src="/assets/img/logo-light.png" class="logo-dark" alt="IndianDetailingGarage" decoding="async" loading="lazy"/>
            <img src="/assets/img/logo.png" class="logo-light" alt="IndianDetailingGarage" decoding="async" loading="lazy"/>
            </span>
        </span>
        <span class="dsnload__row dsnload__row--sibling">
            <span class="dsnload__img">
               <img src="/assets/img/logo-light.png" class="logo-dark" alt="IndianDetailingGarage" decoding="async" loading="lazy"/>
            <img src="/assets/img/logo.png" class="logo-light" alt="IndianDetailingGarage" decoding="async" loading="lazy"/>
            </span>
        </span>


    </div>
    <svg width="100%" height="100%" viewBox="0 0 100 100" class="v-middle" preserveAspectRatio="xMinYMin meet"
         fill="none">
        <linearGradient id="linearColors" x1="0" y1="0" x2="1" y2="1">
            <stop offset="0%" stop-color="var(--theme-color)"></stop>
            <stop offset="50%" stop-color="var(--border-color)"></stop>
            <stop offset="100%" stop-color="var(--assistant-color)"></stop>
        </linearGradient>
        <path class="dsn-progress-path" d="M50,1 a49,49 0 0,1 0,98 a49,49 0 0,1 0,-98"/>
    </svg>
    <div class="loading-circle v-middle">
        <p class="loading-count v-middle">0</p>
    </div>

    <span class="loading-text text-uppercase mt-30 dsn-container">Loading ...</span>
    <div class="bg-load background-section d-flex align-items-end">
        <svg class="dsn-separator-bottom dsn-icon-assistant-color" width="100%" height="100%" viewBox="0 0 100 10"
             preserveAspectRatio="none">
            <path class="path-anim separator__path" data-dsn-to="M 0 0 C 40 0 55 0 100 0 L 0 0 Z"
                  vector-effect="non-scaling-stroke" d="M 0 0 C 40 16 75 10 100 0 L 0 0 Z"></path>
        </svg>
    </div>

</div>

<main id="main_root" class="main-root">

<?php include('common/header.php'); ?>

<header id="dsn_header" class="dsn-header-animation  dsn-full-header v-dark-head">
        <div class="entry-header p-relative over-hidden">
            <div id="hero_image"
                 class="p-absolute dsn-hero-parallax-img over-hidden before-z-index z-index-1 full-width"
                 data-dsn-ajax="img" data-overlay="6">
                <img src="/uploads/<?= $blog['poster'] ?>"
                     class="cover-bg-img transform-3d " alt=""
                     data-dsn-position="50% 50%"
                     sizes="(max-width: 2560px) 100vw, 2560px"/>
            </div>
            <div id="hero_content" class="d-flex p-relative h-100 dsn-hero-parallax-title align-items-end container">
                <div class="content p-relative ">
                    <div class="intro-project w-100">
                        <div class="intro-title ">
                            <!-- <div id="dsn_metas" class="p-relative d-flex justify-content-between ">
                                <div class="metas has-separate p-relative mb-10">
                                    <span>Creative</span>
                                    <span>Photography</span>
                                </div>
                            </div> -->
                            <div id="hero_title">
                                <h1 class="title text-upper" data-dsn-ajax="title"><?= $blog['title'] ?></h1>
                            </div>

                        </div>

                    </div>

                </div>

            </div>

        </div>


        <a href="#page_wrapper" rel="nofollow" class="dsn-scroll-bottom"
           data-dsn-option='{"ease": "power4.inOut" , "duration" : 1.5}'>
            <div class="text">SCROLL</div>
        </a>
    </header>
    <!-- ========== End Header  ========== -->

    <div id="page_wrapper" class="wrapper">

        <div class="root-blog">
            <div class="container ">
                <div class="dsn-posts">


                    <div class="news-content mt-section">
                        <div class="news-content-inner">

                            <div class="post-content">
                                
                                <?= $blog['content'] ?>

                                <div class="post-tags p-relative pb-20">
                                    <?php
                                    $tags = explode(',', $blog['tags']);
                                    foreach ($tags as $tag) {
                                        echo '<a class="fz-16" href="#"><span class="post_tag post_tag">' . $tag . '</span></a>';
                                    }
                                    ?>
                                </div>

                            </div>

                            <div class="pagination-post d-flex align-items-center border-style border-radius mt-section">

                                <!-- <div class="pagination-item w-100 p-20"><a
                                        href="/blog/demo"><span
                                        class="mb-5">PREVIOUS</span><h4 class="title-block word-wrap">Create the
                                    bestworkplace</h4></a></div>

                                <div class="icon p-20 border-right border-left">
                                    <a class="h-100 heading-color" href="#">
                                        <i class="fas fa-th-large" aria-hidden="true"></i>
                                    </a>
                                </div>
                                <div class="pagination-item w-100 p-20 text-right"><a
                                        href="/blog/demo"><span
                                        class="mb-5">NEXT</span><h4 class="title-block word-wrap">Soul Artwork from
                                    Lizzy</h4></a></div> -->
                            </div>

                            <!-- <div class="comments-post section-margin">
                                <div class="comments-area section-margin">
                                    <div class="comments-title">
                                        <h4 class="title-block line-shap line-shap-before">
                                            <span class="line-bg-right">Comments</span>
                                        </h4>
                                    </div>

                                    <ol class="comment-list">
                                        <li class="comment">
                                            <div class="comment-body">
                                                <div class="comment-author">
                                                    <img alt="" src="/assets/img/team/1.jpg">
                                                </div>
                                                <div class="comment-text">

                                                    <div class="comment-info">
                                                        <h6 class="comment-name">
                                                            Diana Torres </h6>
                                                    </div>

                                                    <div class="comment-date">January 23, 2019</div>
                                                    <div class="text-holder">
                                                        <p>Rassa id neque aliquam vestibulum morbi blandit in
                                                            fermentum et
                                                            sollicitudin ac orci
                                                            phasellus egestas tellus velit ut tortor pretium
                                                            viverra
                                                            suspendisse
                                                            potenti nullam ac
                                                            tortor
                                                            eu turpis egestas pretium.</p>
                                                    </div>
                                                    <a class="comment-reply-link" href="#"><i
                                                            class="fas fa-reply"></i>
                                                        reply</a>
                                                </div>
                                            </div>

                                            <ul class="children">
                                                <li class="comment">
                                                    <div class="comment-body">
                                                        <div class="comment-author">
                                                            <img alt="" src="/assets/img/team/1.jpg">
                                                        </div>
                                                        <div class="comment-text">
                                                            <div class="comment-info">
                                                                <h6 class="comment-name">
                                                                    Diana Torres </h6>
                                                            </div>
                                                            <div class="comment-date">January 23, 2019</div>

                                                            <div class="text-holder">
                                                                <p>Rassa id neque aliquam vestibulum morbi
                                                                    blandit in
                                                                    fermentum
                                                                    et sollicitudin ac orci
                                                                    phasellus egestas tellus velit ut tortor
                                                                    pretium viverra
                                                                    suspendisse potenti nullam ac
                                                                    tortor
                                                                    eu turpis egestas pretium.</p>
                                                            </div>
                                                            <a class="comment-reply-link" href="#"><i
                                                                    class="fas fa-reply"></i>
                                                                reply</a>
                                                        </div>
                                                    </div>
                                                </li>
                                            </ul>
                                        </li>

                                        <li class="comment">
                                            <div class="comment-body">
                                                <div class="comment-author">
                                                    <img alt="" src="/assets/img/team/1.jpg">
                                                </div>
                                                <div class="comment-text">
                                                    <div class="comment-info">
                                                        <h6 class="comment-name">
                                                            Diana Torres </h6>
                                                    </div>
                                                    <div class="comment-date">January 23, 2019</div>

                                                    <div class="text-holder">
                                                        <p>Rassa id neque aliquam vestibulum morbi blandit in
                                                            fermentum et
                                                            sollicitudin ac orci
                                                            phasellus egestas tellus velit ut tortor pretium
                                                            viverra
                                                            suspendisse
                                                            potenti nullam ac
                                                            tortor
                                                            eu turpis egestas pretium.</p>
                                                    </div>
                                                    <a class="comment-reply-link" href="#"><i
                                                            class="fas fa-reply"></i>
                                                        reply</a>
                                                </div>
                                            </div>
                                        </li>

                                    </ol>
                                </div>

                                <div class="comments-form dsn-form ">
                                    <div class="comments-title">
                                        <h4 class="title-block line-shap line-shap-before"><span
                                                class="line-bg-right">Comments</span></h4>
                                    </div>

                                    <form id="contact-form" class="form w-100" method="post" data-toggle="validator">
                                        <div class="messages"></div>
                                        <div class="input__wrap controls">
                                            <div class="d-grid grid-md-2">
                                                <div class="form-group dsn-up">
                                                    <div class="entry-box">

                                                        <input id="form_name" type="text" name="name" placeholder="Enter your name ..."
                                                               required="required"
                                                               data-error="name is required."/>
                                                    </div>
                                                    <div class="help-block with-errors"></div>
                                                </div>
                                                <div class="form-group dsn-up">
                                                    <div class="entry-box">

                                                        <input id="form_email" type="email" name="email"
                                                               placeholder="Enter your Email ..."
                                                               required="required" data-error="Valid email is required."/>
                                                    </div>
                                                    <div class="help-block with-errors"></div>
                                                </div>
                                            </div>


                                            <div class="form-group dsn-up">
                                                <div class="entry-box">

                                    <textarea id="form_message" class="form-control" name="message" rows="7"
                                              placeholder="Tell us about you and the world" required="required"
                                              data-error="Please,leave us a message."></textarea>
                                                </div>
                                                <div class="help-block with-errors"></div>
                                            </div>

                                            <div class="d-flex dsn-up">
                                                <div class="image-zoom move-circle border-color-default border-style border-rdu" data-dsn="parallax">
                                                    <input type="submit" value="Post Comment">
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>


                            </div> -->


                        </div>
                    </div>
                </div>

            </div>
        </div>


<?php include('common/footer.php'); ?>

    </div>


</main>

<!-- ========== Cursor ========== -->
<div id="dsn_cursor" class="ball"></div>
<div id="dsn_cursor_inner" class="ball"></div>
<!-- ========== End Cursor ========== -->

<?php include('common/social-style.php'); ?>

<!-- ========== Line BG ========== -->
<div id="line_head"><span class="container"></span></div>
<!-- ========== End Line BG ========== -->

<script src="/assets/js/jquery-3.1.1.min.js"></script>
<script src="/assets/js/plugins.min.js"></script>
<script src="/assets/js/plugins/dsn-grid.min.js"></script>
<script src="/assets/js/custom.js"></script>

</body>

</html>
