<!doctype html>
<html class="no-js" lang="">

<head>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="icon" href="/assets/img/logo-32x32.png" sizes="32x32"/>
    <link rel="icon" href="/assets/img/logo-192x192.png" sizes="192x192"/>

    <title>Modification | Indian Detailing Garage</title>

    <link href="/assets/css/plugins.css" rel="stylesheet"/>
    <link rel="stylesheet" href="/assets/css/style.css">
</head>

<body class="v-dark dsn-ajax dsn-cursor-effect">


<div id="dsn_preloader" class="preloader">

    <div class="dsnload p-absolute">
        <span class="dsnload__row">
            <span class="dsnload__img">
            <img src="/assets/img/logo-light.png" class="logo-dark" alt="IndianDetailingGarage" decoding="async" loading="lazy"/>
            <img src="/assets/img/logo.png" class="logo-light" alt="IndianDetailingGarage" decoding="async" loading="lazy"/>
            </span>
        </span>
        <span class="dsnload__row dsnload__row--sibling">
            <span class="dsnload__img">
                 <img src="/assets/img/logo-light.png" class="logo-dark" alt="IndianDetailingGarage" decoding="async" loading="lazy"/>
            <img src="/assets/img/logo.png" class="logo-light" alt="IndianDetailingGarage" decoding="async" loading="lazy"/>
            </span>
        </span>
        <span class="dsnload__row dsnload__row--sibling">
            <span class="dsnload__img">
                <img src="/assets/img/logo-light.png" class="logo-dark" alt="IndianDetailingGarage" decoding="async" loading="lazy"/>
            <img src="/assets/img/logo.png" class="logo-light" alt="IndianDetailingGarage" decoding="async" loading="lazy"/>
            </span>
        </span>
        <span class="dsnload__row dsnload__row--sibling">
            <span class="dsnload__img">
               <img src="/assets/img/logo-light.png" class="logo-dark" alt="IndianDetailingGarage" decoding="async" loading="lazy"/>
            <img src="/assets/img/logo.png" class="logo-light" alt="IndianDetailingGarage" decoding="async" loading="lazy"/>
            </span>
        </span>


    </div>
    <svg width="100%" height="100%" viewBox="0 0 100 100" class="v-middle" preserveAspectRatio="xMinYMin meet"
         fill="none">
        <linearGradient id="linearColors" x1="0" y1="0" x2="1" y2="1">
            <stop offset="0%" stop-color="var(--theme-color)"></stop>
            <stop offset="50%" stop-color="var(--border-color)"></stop>
            <stop offset="100%" stop-color="var(--assistant-color)"></stop>
        </linearGradient>
        <path class="dsn-progress-path" d="M50,1 a49,49 0 0,1 0,98 a49,49 0 0,1 0,-98"/>
    </svg>
    <div class="loading-circle v-middle">
        <p class="loading-count v-middle">0</p>
    </div>

    <span class="loading-text text-uppercase mt-30 dsn-container">Loading ...</span>
    <div class="bg-load background-section d-flex align-items-end">
        <svg class="dsn-separator-bottom dsn-icon-assistant-color" width="100%" height="100%" viewBox="0 0 100 10"
             preserveAspectRatio="none">
            <path class="path-anim separator__path" data-dsn-to="M 0 0 C 40 0 55 0 100 0 L 0 0 Z"
                  vector-effect="non-scaling-stroke" d="M 0 0 C 40 16 75 10 100 0 L 0 0 Z"></path>
        </svg>
    </div>

</div>

<main id="main_root" class="main-root">

<?php include('common/header.php'); ?>

    <!-- ========== Header Normal========== -->
    <header id="dsn_header" class="dsn-header-animation header-normal ">
        <div class="background-overlay bg-pattern p-absolute left-0 top-0 w-100 h-100"></div>

        <div class="entry-header p-relative over-hidden">

            <div id="hero_content"
                 class="d-flex p-relative h-100 dsn-hero-parallax-title container align-items-center pb-section ">
                <div class="content p-relative ">
                    <div class="intro-project w-100">
                        <div class="intro-title ">

                            <div id="hero_title" class="mt-20">
                                <h1 class="title text-upper">Professional Experience </h1>
                            </div>
                            <p class="mt-20 max-w570">
                                Professional Design Agency to provide solutions
                            </p>
                            <div class="dsn-def-btn dsn-hover-icon dsn-icon-heading-color mt-20 d-flex">
                                <a class="dsn-btn dsn-border border-color-default  background-section effect-ajax has-icon-left"
                                   href="contact.html" data-dsn-text="Contact Us">
                                    <span class="dsn-icon dsn-bg-before btn-icon-left heading-color z-index-1">
                                        <i class="fas fa-angle-right" aria-hidden="true"></i>
                                    </span>
                                    <span class="title-btn p-relative  z-index-1 ">Get Started Now</span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <a href="#page_wrapper" rel="nofollow" class="dsn-scroll-bottom"
           data-dsn-option='{"ease": "power4.inOut" , "duration" : 1.5}'>
            <div class="text">SCROLL</div>
        </a>
    </header>
    <!-- ========== End Header Normal ========== -->

    <div id="page_wrapper" class="wrapper">

        <!-- ========== Portfolio ========== -->
        <div class="p-relative section-margin container">
            <div class="p-relative box-image-parallax dsn-style-cards">
                <div class="root-posts has-filter">

                    <div class="dsn-filtering z-index-1 p-relative w-100 mb-50">
                        <div class="filtering-t">
                            <div class="filtering-wrap">
                                <h5 class="filter-title">
                                    AWESOME DESIGNS </h5>
                                <div class="filtering">
                                    <button class="active" data-filter="*" type="button">
                                        All
                                    </button>
                                    <button type="button" class="dsn-filter-category-production"
                                            data-filter=".production , .category-production">
                                        Production
                                    </button>
                                    <button type="button" class="dsn-filter-category-photography"
                                            data-filter=".photography , .category-photography">
                                        Photography
                                    </button>
                                    <button type="button" class="sm-title-block dsn-filter-category-creative"
                                            data-filter=".creative , .category-creative">CREATIVE
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="dsn-posts dsn-post-type-cards box-image-normal d-grid grid-md-2  dsn-isotope use-filter v-dark-head" data-dsn-gap="60px">

                        <article class="dsn-item-post grid-item over-hidden p-relative box-hover-image production">
                            <div class="box-content d-flex ">
                                <a class="effect-ajax box-image-link bg-shadow" href="project-6.html"
                                   data-dsn-ajax="work" title="HEADPHONES">
                                    <div class="box-image-bg before-z-index dsn-swiper-parallax-transform"
                                         data-overlay="4">
                                        <img class="cover-bg-img" src="/assets/img/portfolio/project6/1.jpg"
                                             alt=""/>
                                    </div>
                                </a>
                                <div class="post-content dsn-bg p-relative z-index-1 d-flex flex-column">
                                    <div class="post-title-info">
                                        <div class="post-meta max-w750">
                                            <div class="p-relative d-inline-block dsn-category dsn-bg metas mb-10 entry-meta">
                                                <span data-separator="&">Production</span>
                                            </div>
                                        </div>
                                        <h2 class="post-title title-block">
                                            <a href="project-6.html" class="effect-ajax"
                                               data-dsn-ajax="work">
                                                HEADPHONES
                                            </a>
                                        </h2>
                                        <p class="section_description mt-15 max-w570 ">
                                            ABOUT THE PROJECT Mode is an audio range designed to provide optimal
                                            performance and comfort for every mode of use. The system utilises a
                                        </p>
                                        <a href="project-6.html"
                                           class="effect-ajax dsn-post-link move-circle border-color-heading"
                                           data-dsn="parallax" data-dsn-ajax="work">
                                            <svg width="24" height="24" xmlns="http://www.w3.org/2000/svg">
                                                <path class="arrow-after"
                                                      d="M21.883 12l-7.527 6.235.644.765 9-7.521-9-7.479-.645.764 7.529 6.236h-21.884v1h21.883z"/>
                                            </svg>
                                        </a>
                                    </div>


                                </div>
                            </div>
                        </article>
                        <article class="dsn-item-post grid-item over-hidden p-relative box-hover-image production photography">
                            <div class="box-content d-flex ">
                                <a class="effect-ajax box-image-link bg-shadow" href="project-5.html"
                                   data-dsn-ajax="work" title="DOG CHOW">
                                    <div class="box-image-bg before-z-index dsn-swiper-parallax-transform"
                                         data-overlay="3">
                                        <img class="cover-bg-img" src="/assets/img/portfolio/project5/1.jpg"
                                             alt=""/>
                                    </div>
                                </a>
                                <div class="post-content dsn-bg p-relative z-index-1 d-flex flex-column">
                                    <div class="post-title-info">
                                        <div class="post-meta max-w750">
                                            <div class="p-relative d-inline-block dsn-category dsn-bg metas mb-10 entry-meta">
                                                <span data-separator=" & ">Photography</span>
                                                <span data-separator=" & ">Production</span>
                                            </div>
                                        </div>
                                        <h2 class="post-title title-block">
                                            <a href="project-5.html" class="effect-ajax"
                                               data-dsn-ajax="work">
                                                DOG CHOW
                                            </a>
                                        </h2>
                                        <p class="section_description mt-15 max-w570 ">
                                            This optional section is only applicable to posts. It is a space for you to
                                            write a summary of the post. Depending on the
                                        </p>
                                        <a href="project-5.html"
                                           class="effect-ajax dsn-post-link move-circle border-color-heading"
                                           data-dsn="parallax" data-dsn-ajax="work">
                                            <svg width="24" height="24" xmlns="http://www.w3.org/2000/svg">
                                                <path class="arrow-after"
                                                      d="M21.883 12l-7.527 6.235.644.765 9-7.521-9-7.479-.645.764 7.529 6.236h-21.884v1h21.883z"/>
                                            </svg>
                                        </a>
                                    </div>


                                </div>
                            </div>


                        </article>
                        <article class="dsn-item-post grid-item over-hidden p-relative box-hover-image production">
                            <div class="box-content d-flex ">
                                <a class="effect-ajax box-image-link bg-shadow" href="project-4.html"
                                   data-dsn-ajax="work" title="OPEN RUN">
                                    <div class="box-image-bg before-z-index dsn-swiper-parallax-transform"
                                         data-overlay="2">
                                        <img class="cover-bg-img" src="/assets/img/portfolio/project4/1.jpg"
                                             alt=""/>
                                    </div>
                                </a>
                                <div class="post-content dsn-bg p-relative z-index-1 d-flex flex-column">
                                    <div class="post-title-info">
                                        <div class="post-meta max-w750">
                                            <div class="p-relative d-inline-block dsn-category dsn-bg metas mb-10 entry-meta">
                                                <span data-separator=" & ">Production</span>
                                            </div>
                                        </div>
                                        <h2 class="post-title title-block">
                                            <a href="project-4.html" class="effect-ajax"
                                               data-dsn-ajax="work">
                                                OPEN RUN
                                            </a>
                                        </h2>
                                        <p class="section_description mt-15 max-w570 ">
                                            ABOUT THE PROJECT Wondour™ was tasked with creating a pair of electronic
                                            glasses that can help legally-blind and low-vision people see again. We’re
                                            helping
                                        </p>
                                        <a href="project-4.html"
                                           class="effect-ajax dsn-post-link move-circle border-color-heading"
                                           data-dsn="parallax" data-dsn-ajax="work">
                                            <svg width="24" height="24" xmlns="http://www.w3.org/2000/svg">
                                                <path class="arrow-after"
                                                      d="M21.883 12l-7.527 6.235.644.765 9-7.521-9-7.479-.645.764 7.529 6.236h-21.884v1h21.883z"/>
                                            </svg>
                                        </a>
                                    </div>


                                </div>
                            </div>


                        </article>
                        <article class="dsn-item-post grid-item over-hidden p-relative box-hover-image production photography">
                            <div class="box-content d-flex ">
                                <a class="effect-ajax box-image-link bg-shadow" href="project-3.html"
                                   data-dsn-ajax="work" title="AUDI RS">
                                    <div class="box-image-bg before-z-index dsn-swiper-parallax-transform"
                                         data-overlay="2">
                                        <img class="cover-bg-img" src="/assets/img/portfolio/project3/1.jpg"
                                             alt=""/>
                                    </div>
                                </a>
                                <div class="post-content dsn-bg p-relative z-index-1 d-flex flex-column">
                                    <div class="post-title-info">
                                        <div class="post-meta max-w750">
                                            <div class="p-relative d-inline-block dsn-category dsn-bg metas mb-10 entry-meta">
                                                <span data-separator=" & ">Photography</span>
                                                <span data-separator=" & ">Production</span>
                                            </div>
                                        </div>
                                        <h2 class="post-title title-block">
                                            <a href="project-3.html" class="effect-ajax"
                                               data-dsn-ajax="work">
                                                AUDI RS
                                            </a>
                                        </h2>
                                        <p class="section_description mt-15 max-w570 ">
                                            This optional section is only applicable to posts. It is a space for you to
                                            write a summary of the post. Depending on the
                                        </p>
                                        <a href="project-3.html"
                                           class="effect-ajax dsn-post-link move-circle border-color-heading"
                                           data-dsn="parallax" data-dsn-ajax="work">
                                            <svg width="24" height="24" xmlns="http://www.w3.org/2000/svg">
                                                <path class="arrow-after"
                                                      d="M21.883 12l-7.527 6.235.644.765 9-7.521-9-7.479-.645.764 7.529 6.236h-21.884v1h21.883z"/>
                                            </svg>
                                        </a>
                                    </div>

                                </div>
                            </div>


                        </article>
                        <article class="dsn-item-post grid-item over-hidden p-relative box-hover-image photography">
                            <div class="box-content d-flex ">
                                <a class="effect-ajax box-image-link bg-shadow" href="project-2.html"
                                   data-dsn-ajax="work" title="MEN FASHION">
                                    <div class="box-image-bg before-z-index dsn-swiper-parallax-transform"
                                         data-overlay="4">
                                        <img class="cover-bg-img" src="/assets/img/portfolio/project2/1.jpg"
                                             alt=""/>
                                    </div>
                                </a>
                                <div class="post-content dsn-bg p-relative z-index-1 d-flex flex-column">
                                    <div class="post-title-info">
                                        <div class="post-meta max-w750">
                                            <div class="p-relative d-inline-block dsn-category dsn-bg metas mb-10 entry-meta">
                                                <span data-separator=" & ">Photography</span>
                                            </div>
                                        </div>
                                        <h2 class="post-title title-block">
                                            <a href="project-2.html" class="effect-ajax"
                                               data-dsn-ajax="work">
                                                MEN FASHION
                                            </a>
                                        </h2>
                                        <p class="section_description mt-15 max-w570 ">
                                            Service Photographer Industry Daniel Jaramillo Published June 15th 2022
                                            Caption #1 Caption #2 Caption #3 How is your visual identity? we give
                                            fashion forward
                                        </p>
                                        <a href="project-2.html"
                                           class="effect-ajax dsn-post-link move-circle border-color-heading"
                                           data-dsn="parallax" data-dsn-ajax="work">
                                            <svg width="24" height="24" xmlns="http://www.w3.org/2000/svg">
                                                <path class="arrow-after"
                                                      d="M21.883 12l-7.527 6.235.644.765 9-7.521-9-7.479-.645.764 7.529 6.236h-21.884v1h21.883z"/>
                                            </svg>
                                        </a>
                                    </div>

                                </div>
                            </div>


                        </article>
                        <article class="dsn-item-post grid-item over-hidden p-relative box-hover-image creative photography">
                            <div class="box-content d-flex ">
                                <a class="effect-ajax box-image-link bg-shadow" href="project-1.html"
                                   data-dsn-ajax="work" title="VISIONAID">
                                    <div class="box-image-bg before-z-index dsn-swiper-parallax-transform"
                                         data-overlay="4">
                                        <img class="cover-bg-img" src="/assets/img/portfolio/project1/1.jpg"
                                             alt=""/>
                                    </div>
                                </a>
                                <div class="post-content dsn-bg p-relative z-index-1 d-flex flex-column">
                                    <div class="post-title-info">
                                        <div class="post-meta max-w750">
                                            <div class="p-relative d-inline-block dsn-category dsn-bg metas mb-10 entry-meta">
                                                <span data-separator=" & ">Creative</span>
                                                <span data-separator=" & ">Photography</span>
                                            </div>
                                        </div>
                                        <h2 class="post-title title-block">
                                            <a href="project-1.html" class="effect-ajax"
                                               data-dsn-ajax="work">
                                                VISIONAID
                                            </a>
                                        </h2>
                                        <p class="section_description mt-15 max-w570 ">
                                            Service Photographer Industry Daniel Jaramillo Published June 15th 2022
                                            Caption #1 Caption #2 Caption #3 How is your visual identity? we give
                                            fashion forward
                                        </p>
                                        <a href="project-1.html"
                                           class="effect-ajax dsn-post-link move-circle border-color-heading"
                                           data-dsn="parallax" data-dsn-ajax="work">
                                            <svg width="24" height="24" xmlns="http://www.w3.org/2000/svg">
                                                <path class="arrow-after"
                                                      d="M21.883 12l-7.527 6.235.644.765 9-7.521-9-7.479-.645.764 7.529 6.236h-21.884v1h21.883z"/>
                                            </svg>
                                        </a>
                                    </div>


                                </div>
                            </div>


                        </article>


                    </div>
                </div>
            </div>
        </div>
        <!-- ========== End Portfolio ========== -->


<?php include('common/footer.php'); ?>

    </div>
</main>

<!-- ========== Cursor ========== -->
<div id="dsn_cursor" class="ball"></div>
<div id="dsn_cursor_inner" class="ball"></div>
<!-- ========== End Cursor ========== -->

<?php include('common/social-style.php'); ?>

<!-- ========== Line BG ========== -->
<div id="line_head"><span class="container"></span></div>
<!-- ========== End Line BG ========== -->

<script src="/assets/js/jquery-3.1.1.min.js"></script>
<script src="/assets/js/plugins.min.js"></script>
<script src="/assets/js/plugins/dsn-grid.min.js"></script>
<script src="/assets/js/custom.js"></script>

</body>

</html>
